#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

use 
	Symfony\Component\Console\Application;

use
	Acme\User;

$application = new Application();
$application->add(new User\Create);
$application->add(new User\Update);
$application->add(new User\Delete);
$application->add(new User\View);
$application->run();